const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.TileMovement,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Behaviors.MoveTo,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.Anchor,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.TileMovement.Cnds.IsMovingDirection,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.TileMovement.Cnds.IsMoving,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.TileMovement.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.TileMovement.Acts.SetDefaultControls,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.TileMovement.Acts.SetIgnoreInput,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Text.Acts.Destroy,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.solid.Acts.SetEnabled
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Collisions: 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{TileMovement: 0},
	{PlayerCollisions: 0},
	{DragDrop: 0},
	{acespade: 0},
	{aceheart: 0},
	{acediamonds: 0},
	{aceclubs: 0},
	{Dice1: 0},
	{Dice2: 0},
	{BoxPushEnd: 0},
	{BoxPush: 0},
	{DecorationArea: 0},
	{NewsClip: 0},
	{PlaceHolderText: 0},
	{BlackoutArea: 0},
	{SlotMachineRed: 0},
	{SlotMachineCollision: 0},
	{SlotMachineYellow: 0},
	{Pin: 0},
	{Player: 0},
	{CasinoMainfloor: 0},
	{BarChair: 0},
	{Chair: 0},
	{Newspaper2: 0},
	{Newspaper1: 0},
	{MoveTo: 0},
	{Carter: 0},
	{NPC: 0},
	{Vent: 0},
	{NewspaperText1: 0},
	{ElevatorPanel: 0},
	{Buttonnnnn: 0},
	{Cards: 0},
	{CardTable: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{HUDText: 0},
	{InteractText: 0},
	{Money: 0},
	{HUD: 0},
	{HUDVentOpen: 0},
	{HUDFloor: 0},
	{Buttons1: 0},
	{Buttons2: 0},
	{Audio: 0},
	{Water: 0},
	{WoodFloors: 0},
	{Buttonnnnn2: 0},
	{Buttonnnnn3: 0},
	{BlackjackTable1: 0},
	{ParkingLot: 0},
	{ParkingLot2: 0},
	{ParkingLot3: 0},
	{ParkingLot4: 0},
	{Anchor: 0},
	{DiceRollResultstatic: 0},
	{DiceRollResultvariable: 0},
	{HUDInteractText: 0},
	{HUDCarterText: 0},
	{HUDCarterText2: 0},
	{TitleScreenBackground: 0},
	{aceclubs2: 0},
	{acediamonds2: 0},
	{acespade2: 0},
	{aceheart2: 0},
	{Dice3: 0},
	{Dice4: 0},
	{StartScreenText: 0},
	{StartScreenText2: 0},
	{Flash: 0},
	{StartScreenText3: 0},
	{StartScreenText4: 0},
	{StartScreenText5: 0},
	{StartScreenText6: 0},
	{StoryStartText: 0},
	{ContinueText: 0},
	{StartScreenText7: 0},
	{Backbutton1: 0},
	{Dashes: 0},
	{HUDCarterText3: 0},
	{CutsceneLine: 0},
	{HUDCarterText4: 0},
	{CarterOffScreen: 0},
	{CutsceneLine2: 0},
	{CasinoDoorOpening: 0},
	{NighttimeTint: 0},
	{FlowerBed: 0},
	{NewspaperText2: 0},
	{NewspaperTextHeadline1: 0},
	{NewspaperHeadline2: 0},
	{HotelRoomDoor: 0},
	{ElevatorHallway: 0},
	{RoomDoor: 0},
	{EugineWalkerText: 0},
	{JasonFisherText: 0},
	{Eugine: 0},
	{WalkerCollision: 0},
	{TextBoxBackground: 0},
	{TextBoxBackground2: 0},
	{Bed: 0},
	{DiceTableCollisions: 0},
	{PoolTable: 0},
	{DiceTable: 0},
	{TrickDice: 0},
	{BlueSlots: 0},
	{Mirror: 0},
	{Phone: 0},
	{Table: 0},
	{Dice6: 0},
	{Dice5: 0},
	{Door: 0},
	{Levelend: 0},
	{BoxReset: 0},
	{BoxPushStart: 0},
	{HUDText2: 0},
	{MirrorText: 0},
	{PhoneText: 0},
	{Venttext: 0},
	{Door2: 0},
	{Door3: 0},
	{LevelButtons: 0},
	{LevelButtons2: 0},
	{LevelButtons3: 0},
	{LevelButtons4: 0},
	{LevelButtons5: 0},
	{LevelButtons6: 0},
	{Crate: 0},
	{Crate2: 0},
	{CarterWallsText: 0},
	{TrickDice2: 0},
	{Tarp: 0},
	{Tape: 0},
	{Buttons3: 0},
	{Buttons4: 0},
	{TapeTarpText: 0},
	{TapeTarpText2: 0},
	{BlackedoutMirror: 0},
	{TrickDiceHUD: 0},
	{TrickDiceOptions: 0},
	{TrickDiceOptions2: 0},
	{TrickDiceOptions3: 0},
	{Dice7: 0},
	{Dice8: 0},
	{Dice9: 0},
	{Dice10: 0},
	{Water2: 0},
	{Flower: 0},
	{Pot: 0},
	{Water3: 0},
	{Water4: 0},
	{Water5: 0},
	{LevelButtons7: 0},
	{LevelButtons8: 0},
	{Door6: 0},
	{Door7: 0},
	{Buttons5: 0},
	{Buttons6: 0},
	{Buttons7: 0},
	{Buttons8: 0},
	{Buttons9: 0},
	{Buttons10: 0},
	{Buttons11: 0},
	{Buttons12: 0},
	{Fountain: 0},
	{NPC3: 0},
	{NPC4: 0},
	{NPC5: 0},
	{ElevatorDoor: 0},
	{Car: 0},
	{Bed2: 0},
	{Phone2: 0},
	{Itworked: 0},
	{Newspaper3: 0},
	{Newspaper4: 0},
	{NewspaperHeadline3: 0},
	{NewspaperHeadline4: 0},
	{NewspaperText3: 0},
	{NewspaperText4: 0},
	{Crate3: 0},
	{CrateText: 0},
	{CarterOffScreen2: 0},
	{ManaForgeLOGOSPRITE: 0},
	{CardFamily: 0},
	{VentFamily: 0},
	{Panel: 0},
	{Buttons: 0},
	{Newspapers: 0},
	{diceRoll: 0},
	{diceRoll2: 0},
	{LEVELVARIABLE: 0},
	{DiceRollable: 0},
	{LevelsPlayed: 0},
	{TapeTarp: 0}
];

self.InstanceType = {
	Collisions: class extends self.ISpriteInstance {},
	PlayerCollisions: class extends self.ISpriteInstance {},
	acespade: class extends self.ISpriteInstance {},
	aceheart: class extends self.ISpriteInstance {},
	acediamonds: class extends self.ISpriteInstance {},
	aceclubs: class extends self.ISpriteInstance {},
	Dice1: class extends self.ISpriteInstance {},
	Dice2: class extends self.ISpriteInstance {},
	BoxPushEnd: class extends self.ISpriteInstance {},
	BoxPush: class extends self.ISpriteInstance {},
	DecorationArea: class extends self.ISpriteInstance {},
	NewsClip: class extends self.ISpriteInstance {},
	PlaceHolderText: class extends self.ITextInstance {},
	BlackoutArea: class extends self.ISpriteInstance {},
	SlotMachineRed: class extends self.ISpriteInstance {},
	SlotMachineCollision: class extends self.ISpriteInstance {},
	SlotMachineYellow: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	CasinoMainfloor: class extends self.ISpriteInstance {},
	BarChair: class extends self.ISpriteInstance {},
	Chair: class extends self.ISpriteInstance {},
	Newspaper2: class extends self.ISpriteInstance {},
	Newspaper1: class extends self.ISpriteInstance {},
	Carter: class extends self.ISpriteInstance {},
	NPC: class extends self.ISpriteInstance {},
	Vent: class extends self.ISpriteInstance {},
	NewspaperText1: class extends self.ITextInstance {},
	ElevatorPanel: class extends self.ISpriteInstance {},
	Buttonnnnn: class extends self.ISpriteInstance {},
	Cards: class extends self.ISpriteInstance {},
	CardTable: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	HUDText: class extends self.ITextInstance {},
	InteractText: class extends self.ITextInstance {},
	Money: class extends self.ISpriteInstance {},
	HUD: class extends self.ISpriteInstance {},
	HUDVentOpen: class extends self.ISpriteInstance {},
	HUDFloor: class extends self.ISpriteInstance {},
	Buttons1: class extends self.ISpriteInstance {},
	Buttons2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Water: class extends self.ISpriteInstance {},
	WoodFloors: class extends self.ISpriteInstance {},
	Buttonnnnn2: class extends self.ISpriteInstance {},
	Buttonnnnn3: class extends self.ISpriteInstance {},
	BlackjackTable1: class extends self.ISpriteInstance {},
	ParkingLot: class extends self.ISpriteInstance {},
	ParkingLot2: class extends self.ISpriteInstance {},
	ParkingLot3: class extends self.ISpriteInstance {},
	ParkingLot4: class extends self.ISpriteInstance {},
	DiceRollResultstatic: class extends self.ITextInstance {},
	DiceRollResultvariable: class extends self.ITextInstance {},
	HUDInteractText: class extends self.ITextInstance {},
	HUDCarterText: class extends self.ITextInstance {},
	HUDCarterText2: class extends self.ITextInstance {},
	TitleScreenBackground: class extends self.ISpriteInstance {},
	aceclubs2: class extends self.ISpriteInstance {},
	acediamonds2: class extends self.ISpriteInstance {},
	acespade2: class extends self.ISpriteInstance {},
	aceheart2: class extends self.ISpriteInstance {},
	Dice3: class extends self.ISpriteInstance {},
	Dice4: class extends self.ISpriteInstance {},
	StartScreenText: class extends self.ITextInstance {},
	StartScreenText2: class extends self.ITextInstance {},
	StartScreenText3: class extends self.ITextInstance {},
	StartScreenText4: class extends self.ITextInstance {},
	StartScreenText5: class extends self.ITextInstance {},
	StartScreenText6: class extends self.ITextInstance {},
	StoryStartText: class extends self.ITextInstance {},
	ContinueText: class extends self.ITextInstance {},
	StartScreenText7: class extends self.ITextInstance {},
	Backbutton1: class extends self.ITextInstance {},
	Dashes: class extends self.ITextInstance {},
	HUDCarterText3: class extends self.ITextInstance {},
	CutsceneLine: class extends self.ISpriteInstance {},
	HUDCarterText4: class extends self.ITextInstance {},
	CarterOffScreen: class extends self.ISpriteInstance {},
	CutsceneLine2: class extends self.ISpriteInstance {},
	CasinoDoorOpening: class extends self.ISpriteInstance {},
	NighttimeTint: class extends self.ISpriteInstance {},
	FlowerBed: class extends self.ISpriteInstance {},
	NewspaperText2: class extends self.ITextInstance {},
	NewspaperTextHeadline1: class extends self.ITextInstance {},
	NewspaperHeadline2: class extends self.ITextInstance {},
	HotelRoomDoor: class extends self.ISpriteInstance {},
	ElevatorHallway: class extends self.ISpriteInstance {},
	RoomDoor: class extends self.ISpriteInstance {},
	EugineWalkerText: class extends self.ITextInstance {},
	JasonFisherText: class extends self.ITextInstance {},
	Eugine: class extends self.ISpriteInstance {},
	WalkerCollision: class extends self.ISpriteInstance {},
	TextBoxBackground: class extends self.ISpriteInstance {},
	TextBoxBackground2: class extends self.ISpriteInstance {},
	Bed: class extends self.ISpriteInstance {},
	DiceTableCollisions: class extends self.ISpriteInstance {},
	PoolTable: class extends self.ISpriteInstance {},
	DiceTable: class extends self.ISpriteInstance {},
	TrickDice: class extends self.ISpriteInstance {},
	BlueSlots: class extends self.ISpriteInstance {},
	Mirror: class extends self.ISpriteInstance {},
	Phone: class extends self.ISpriteInstance {},
	Table: class extends self.ISpriteInstance {},
	Dice6: class extends self.ISpriteInstance {},
	Dice5: class extends self.ISpriteInstance {},
	Door: class extends self.ISpriteInstance {},
	Levelend: class extends self.ISpriteInstance {},
	BoxReset: class extends self.ISpriteInstance {},
	BoxPushStart: class extends self.ISpriteInstance {},
	HUDText2: class extends self.ITextInstance {},
	MirrorText: class extends self.ITextInstance {},
	PhoneText: class extends self.ITextInstance {},
	Venttext: class extends self.ITextInstance {},
	Door2: class extends self.ISpriteInstance {},
	Door3: class extends self.ISpriteInstance {},
	LevelButtons: class extends self.ISpriteInstance {},
	LevelButtons2: class extends self.ISpriteInstance {},
	LevelButtons3: class extends self.ISpriteInstance {},
	LevelButtons4: class extends self.ISpriteInstance {},
	LevelButtons5: class extends self.ISpriteInstance {},
	LevelButtons6: class extends self.ISpriteInstance {},
	Crate: class extends self.ISpriteInstance {},
	Crate2: class extends self.ISpriteInstance {},
	CarterWallsText: class extends self.ITextInstance {},
	TrickDice2: class extends self.ISpriteInstance {},
	Tarp: class extends self.ISpriteInstance {},
	Tape: class extends self.ISpriteInstance {},
	Buttons3: class extends self.ISpriteInstance {},
	Buttons4: class extends self.ISpriteInstance {},
	TapeTarpText: class extends self.ITextInstance {},
	TapeTarpText2: class extends self.ITextInstance {},
	BlackedoutMirror: class extends self.ISpriteInstance {},
	TrickDiceHUD: class extends self.ISpriteInstance {},
	TrickDiceOptions: class extends self.ITextInstance {},
	TrickDiceOptions2: class extends self.ITextInstance {},
	TrickDiceOptions3: class extends self.ITextInstance {},
	Dice7: class extends self.ISpriteInstance {},
	Dice8: class extends self.ISpriteInstance {},
	Dice9: class extends self.ISpriteInstance {},
	Dice10: class extends self.ISpriteInstance {},
	Water2: class extends self.ISpriteInstance {},
	Flower: class extends self.ISpriteInstance {},
	Pot: class extends self.ISpriteInstance {},
	Water3: class extends self.ISpriteInstance {},
	Water4: class extends self.ISpriteInstance {},
	Water5: class extends self.ISpriteInstance {},
	LevelButtons7: class extends self.ISpriteInstance {},
	LevelButtons8: class extends self.ISpriteInstance {},
	Door6: class extends self.ISpriteInstance {},
	Door7: class extends self.ISpriteInstance {},
	Buttons5: class extends self.ISpriteInstance {},
	Buttons6: class extends self.ISpriteInstance {},
	Buttons7: class extends self.ISpriteInstance {},
	Buttons8: class extends self.ISpriteInstance {},
	Buttons9: class extends self.ISpriteInstance {},
	Buttons10: class extends self.ISpriteInstance {},
	Buttons11: class extends self.ISpriteInstance {},
	Buttons12: class extends self.ISpriteInstance {},
	Fountain: class extends self.ISpriteInstance {},
	NPC3: class extends self.ISpriteInstance {},
	NPC4: class extends self.ISpriteInstance {},
	NPC5: class extends self.ISpriteInstance {},
	ElevatorDoor: class extends self.ISpriteInstance {},
	Car: class extends self.ISpriteInstance {},
	Bed2: class extends self.ISpriteInstance {},
	Phone2: class extends self.ISpriteInstance {},
	Itworked: class extends self.ISpriteInstance {},
	Newspaper3: class extends self.ISpriteInstance {},
	Newspaper4: class extends self.ISpriteInstance {},
	NewspaperHeadline3: class extends self.ITextInstance {},
	NewspaperHeadline4: class extends self.ITextInstance {},
	NewspaperText3: class extends self.ITextInstance {},
	NewspaperText4: class extends self.ITextInstance {},
	Crate3: class extends self.ISpriteInstance {},
	CrateText: class extends self.ITextInstance {},
	CarterOffScreen2: class extends self.ISpriteInstance {},
	ManaForgeLOGOSPRITE: class extends self.ISpriteInstance {},
	CardFamily: class extends self.ISpriteInstance {},
	VentFamily: class extends self.ISpriteInstance {},
	Panel: class extends self.ISpriteInstance {}
}